apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: kegistry
spec:
  minReplicas: 2
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kegistry
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          averageUtilization: 60
          type: Utilization
    - type: Resource
      resource:
        name: cpu
        target:
          averageUtilization: 60
          type: Utilization
