name: Lint PR

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  validate-title:
    name: Validate Title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            fix
            feat
            chore
          requireScope: false
          subjectPattern: ^(?![a-z]).+$
